UDEVICEX_PATH = ../..

binary = redist

# Targets
objects = test_redist.o celllist.o particle_exchanger.o particle_redistributor.o \
	particle_vector.o object_vector.o uniform_ic.o stacktrace_explicit.o
	
include ../../makefiles/Makefile.base