UDEVICEX_PATH = ../..

binary = halo

# Targets
objects = test_obj_halo.o celllist.o scan.o pugixml.o \
	particle_exchanger.o object_halo_exchanger.o \
	particle_vector.o object_vector.o rigid_ellipsoid_object_vector.o
	
include ../../makefiles/Makefile.base