#!/bin/bash

# TEST: restart.id.single
mir.restart.id tests/example 1
cat tests/example/file.txt > restart.out.txt

# TEST: restart.id.notfound
mir.restart.id tests/example 99 > restart.out.txt

# TEST: restart.id.multiple
mir.restart.id tests/example2 1
cat tests/example2/file0.txt >  restart.out.txt
cat tests/example2/file1.txt >> restart.out.txt

