UDEVICEX_PATH = ../..

binary = halo

# Targets
objects = test_halo.o celllist.o particle_exchanger.o particle_halo_exchanger.o \
	particle_vector.o object_vector.o uniform_ic.o stacktrace_explicit.o
	
include ../../makefiles/Makefile.base