UDEVICEX_PATH = ../..

binary = genwall

# Targets
objects = main.o argument_parser.o celllist.o simulation.o task_scheduler.o pugixml.o stacktrace_explicit.o \
	uniform.o \
	sampler.o \
	particle_exchanger.o particle_halo_exchanger.o particle_redistributor.o object_halo_exchanger.o object_redistributor.o object_forces_reverse_exchanger.o \
	particle_vector.o object_vector.o sdf.o \
	simple_stationary_wall.o \
	freeze_particles.o
		
include ../../makefiles/Makefile.base