UDEVICEX_PATH = ../..

binary = genwall

# Targets
objects = main_md.o argument_parser.o celllist.o simulation.o task_scheduler.o pugixml.o stacktrace_explicit.o \
	uniform_ic.o \
	sampler.o \
	particle_exchanger.o particle_halo_exchanger.o particle_redistributor.o object_halo_exchanger.o object_redistributor.o object_forces_reverse_exchanger.o \
	belonging.o \
	particle_vector.o object_vector.o \
	simple_stationary_wall.o wall_with_velocity.o sdf.o pairwise.o \
	freeze_particles.o
		
include ../../makefiles/Makefile.base