#! /bin/bash

usage() {
    cat <<EOF
wrapper for hostname shell command
this is used to choose configuration in other
tools such as the `load` tool

usage:
host
EOF
    exit 1
}

if test $# -ne 0; then usage; fi

case $(hostname) in
    falcon*)
        echo falcon
	;;
    panda*)
        echo panda
	;;
    barry*)
	echo barry
	;;
    daint*)
	echo daint
	;;
    hal.* |  glados.*)
        echo harvard.servers
        ;;
    *rc.fas.harvard.edu)
        echo cannon
        ;;
    holygpu7c1101 | holygpu7c1102)
        echo grace
        ;;
    *)
	echo __default
	;;
esac
