#!/bin/bash

a=5
DRYRUN= mir.batch "$@" <<EOF
mir.run --runargs "- n 1" echo $a
EOF

# TEST: batch.dryrun.0
# cd tests
# ./dryrun > script.out.txt

# TEST: batch.dryrun.1
# cd tests
# ./dryrun --opt0=1 --opt1=5 > script.out.txt
