UDEVICEX_PATH = ../..

binary = mesh_leak

# Targets
objects = test_mesh_leak.o particle_vector.o object_vector.o mesh.o from_mesh.o \
		  stacktrace_explicit.o rigid_object_vector.o celllist.o rigid_ic.o rigid_vv.o

include ../../makefiles/Makefile.base
