UDEVICEX_PATH = ../..

binary = udevicex

# Targets
objects = main.o \
	argument_parser.o pugixml.o stacktrace_explicit.o \
	celllist.o mesh.o parser.o postproc.o simulation.o task_scheduler.o udevicex.o \
	from_mesh.o from_ellipsoid.o belonging.o ellipsoid_belonging.o mesh_belonging.o \
	ellipsoid_ic.o uniform_ic.o rbcs_ic.o \
	const_omega.o rigid_vv.o vv.o oscillate.o \
	pairwise.o rbc.o \
	particle_exchanger.o particle_halo_exchanger.o particle_redistributor.o object_halo_exchanger.o object_redistributor.o object_forces_reverse_exchanger.o \
	particle_vector.o object_vector.o \
	simple_stationary_wall.o wall_with_velocity.o sdf.o \
	write_xdmf.o dumpavg.o stats.o temperaturize.o dumpxyz.o dump_obj_position.o impose_velocity.o pin_object.o
	
include ../../makefiles/Makefile.base