UDEVICEX_PATH = ../..

binary = udevicex

# Targets
objects = main.o argument_parser.o celllist.o parser.o postproc.o scan.o simulation.o task_scheduler.o udevicex.o \
	from_mesh.o from_ellipsoid.o \
	const_omega.o rigid_vv.o vv_const_dp.o vv.o \
	dpd.o lj.o sampler.o \
	particle_exchanger.o particle_halo_exchanger.o particle_redistributor.o object_halo_exchanger.o object_redistributor.o object_forces_reverse_exchanger.o \
	sdf_wall.o \
	write_xdmf.o dumpavg.o stats.o temperaturize.o
	
include ../../makefiles/Makefile.base