cell-placement:	main.cpp
	$(CXX) -std=c++11 -O3 -fopenmp main.cpp -o cell-placement

check: check.cpp
	$(CXX) -std=c++11 -O3 check.cpp -o check

clean:
	rm -f cell-placement check

.PHONY = cell-placement
